# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
