# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 19:10
from __future__ import unicode_literals

from django.db import migrations, models

last_id=0
def count_id():
    return ++last_id
    
class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, default=count_id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
